create table if not exists customer_leads (
  id integer generated by default as identity primary key,
  "cozeRecordId" text unique,
  "sysPlatform" text,
  uuid text,
  "bstudioCreateTime" timestamptz,
  "userId" text not null,
  nickname text,
  height text,
  weight text,
  "targetWeight" text,
  "mainConcern" text,
  "riskFlag" boolean not null default false,
  "riskType" text,
  "intentLevel" text,
  "currentStage" text,
  "recommendedPackage" text,
  "lastUserMessage" text,
  "lastAiReply" text,
  "leadSummary" text,
  "nextAction" text,
  "followUpTime" timestamptz,
  "profileJson" jsonb,
  owner text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create index if not exists "customer_leads_userId_idx" on customer_leads ("userId");
create index if not exists "customer_leads_cozeRecordId_idx" on customer_leads ("cozeRecordId");
create index if not exists "customer_leads_intentLevel_idx" on customer_leads ("intentLevel");
create index if not exists "customer_leads_nextAction_idx" on customer_leads ("nextAction");
create index if not exists "customer_leads_updatedAt_idx" on customer_leads ("updatedAt");

create table if not exists conversation_events (
  id integer generated by default as identity primary key,
  "cozeRecordId" text unique,
  "sysPlatform" text,
  uuid text,
  "bstudioCreateTime" timestamptz,
  "eventId" text,
  "leadId" text,
  "userId" text not null,
  "eventType" text,
  "userMessage" text,
  "aiReply" text,
  "intentLevel" text,
  "nextAction" text,
  "riskFlag" boolean not null default false,
  "riskType" text,
  "messageSummary" text,
  "createdAt" timestamptz not null default now()
);

create index if not exists "conversation_events_userId_idx" on conversation_events ("userId");
create index if not exists "conversation_events_cozeRecordId_idx" on conversation_events ("cozeRecordId");
create index if not exists "conversation_events_leadId_idx" on conversation_events ("leadId");
create index if not exists "conversation_events_intentLevel_idx" on conversation_events ("intentLevel");
create index if not exists "conversation_events_createdAt_idx" on conversation_events ("createdAt");

create table if not exists kb_miss_questions (
  id integer generated by default as identity primary key,
  "cozeRecordId" text unique,
  "sysPlatform" text,
  uuid text,
  "bstudioCreateTime" timestamptz,
  "missId" text,
  "userId" text,
  "chatHistory" text,
  "aiReply" text,
  nickname text,
  "missReason" text,
  route text,
  status text,
  "suggestedAnswer" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "userMessage" text
);

create index if not exists "kb_miss_questions_userId_idx" on kb_miss_questions ("userId");
create index if not exists "kb_miss_questions_cozeRecordId_idx" on kb_miss_questions ("cozeRecordId");
create index if not exists "kb_miss_questions_status_idx" on kb_miss_questions (status);
create index if not exists "kb_miss_questions_route_idx" on kb_miss_questions (route);
create index if not exists "kb_miss_questions_createdAt_idx" on kb_miss_questions ("createdAt");

create table if not exists coze_sync_states (
  id integer generated by default as identity primary key,
  source text not null unique,
  "databaseId" text not null,
  "cursorField" text not null,
  "lastSyncAt" timestamptz,
  "lastRunAt" timestamptz,
  "lastStatus" text,
  "lastError" text,
  "fetchedCount" integer not null default 0,
  "createdCount" integer not null default 0,
  "updatedCount" integer not null default 0,
  "skippedCount" integer not null default 0,
  "updatedAt" timestamptz not null default now(),
  "createdAt" timestamptz not null default now()
);
